{"name": "test_login_3[3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_fixture.TestLogin object at 0x000001AA3759B518>, data = 3\n\n    def test_login_3(self, data):\n        \"\"\"记住密码登录\"\"\"\n        allure.attach(\"输入用户名\", \"输入用户名username_3\")\n        print(\"输入用户名\")\n        allure.attach(\"输入密码\", \"输入用户名password_3\")\n        print(\"输入密码\")\n        allure.attach(\"点击登录\", \"登录成功\")\n        print(\"点击登录\")\n        print(data)\n>       assert False\nE       assert False\n\nscripts\\test_fixture.py:40: AssertionError"}, "description": "记住密码登录", "attachments": [{"name": "输入用户名username_3", "source": "f32b888a-b534-4bd1-95b4-c2f21c4ba3fc-attachment.attach"}, {"name": "输入用户名password_3", "source": "512e1fee-4037-4aa0-9278-f529fe864f50-attachment.attach"}, {"name": "登录成功", "source": "8c02e6e2-35e0-4e0f-811c-88acbdc7ff3c-attachment.attach"}], "parameters": [{"name": "data", "value": "3"}], "start": 1575025910720, "stop": 1575025910725, "uuid": "02d6127e-759b-4a83-83ab-f2ed584f4a26", "historyId": "c19157f3bc16370952e1078628fc2183", "testCaseId": "133a8e3ccd283ba22e290157fe855949", "fullName": "scripts.test_fixture.TestLogin#test_login_3", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_fixture"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47A72RD"}, {"name": "thread", "value": "8984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_fixture"}]}