{"name": "test_login_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_login_rerun.TestLogin object at 0x000002C7D291D080>\n\n    def test_login_1(self):\n        \"\"\"记住密码登录\"\"\"\n        print(\"test_login_1记住密码登录\")\n        num = random.randint(1,2)\n        if num % 2:\n            assert True\n        else:\n>           assert False  # 断言失败\nE           assert False\n\nscripts\\test_login_rerun.py:13: AssertionError"}, "description": "记住密码登录", "start": 1575025966293, "stop": 1575025966293, "uuid": "159b6f9e-e774-4b65-9438-90af4e3ef41b", "historyId": "4eba568bb2ae9c6747740f157128bdfe", "testCaseId": "94c7bce98e70b18e52ea0a4586601440", "fullName": "scripts.test_login_rerun.TestLogin#test_login_1", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login_rerun"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47A72RD"}, {"name": "thread", "value": "6108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login_rerun"}]}