{"name": "test_login_3[1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_fixture.TestLogin object at 0x000001A83A7F46A0>, data = 1\n\n    def test_login_3(self, data):\n        \"\"\"记住密码登录\"\"\"\n        allure.attach(\"输入用户名\", \"输入用户名username_3\")\n        print(\"输入用户名\")\n        allure.attach(\"输入密码\", \"输入用户名password_3\")\n        print(\"输入密码\")\n        allure.attach(\"点击登录\", \"登录成功\")\n        print(\"点击登录\")\n        print(data)\n>       assert False\nE       assert False\n\nscripts\\test_fixture.py:40: AssertionError"}, "description": "记住密码登录", "attachments": [{"name": "输入用户名username_3", "source": "9d7d7585-35ff-4047-a746-3c942f91c107-attachment.attach"}, {"name": "输入用户名password_3", "source": "af086cfe-53e5-4518-84e6-f172e2ba3d16-attachment.attach"}, {"name": "登录成功", "source": "7acb92cc-334f-4abf-a2da-fa545ea0e21b-attachment.attach"}], "parameters": [{"name": "data", "value": "1"}], "start": 1575025869114, "stop": 1575025869122, "uuid": "d56e4b79-a6fd-4042-bab7-f903cf0a45ff", "historyId": "71b61181cb38681bfc85e48c867026dd", "testCaseId": "133a8e3ccd283ba22e290157fe855949", "fullName": "scripts.test_fixture.TestLogin#test_login_3", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_fixture"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47A72RD"}, {"name": "thread", "value": "12696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_fixture"}]}