{"name": "test_login_3[1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_fixture.TestLogin object at 0x000002C7D28B9EF0>, data = 1\n\n    def test_login_3(self, data):\n        \"\"\"记住密码登录\"\"\"\n        allure.attach(\"输入用户名\", \"输入用户名username_3\")\n        print(\"输入用户名\")\n        allure.attach(\"输入密码\", \"输入用户名password_3\")\n        print(\"输入密码\")\n        allure.attach(\"点击登录\", \"登录成功\")\n        print(\"点击登录\")\n        print(data)\n>       assert False\nE       assert False\n\nscripts\\test_fixture.py:40: AssertionError"}, "description": "记住密码登录", "attachments": [{"name": "输入用户名username_3", "source": "ef8b9428-1bb6-4049-a9ee-81d029f3874d-attachment.attach"}, {"name": "输入用户名password_3", "source": "7117c496-6e3c-4b13-a748-264d0e205ffa-attachment.attach"}, {"name": "登录成功", "source": "d008c517-72ba-4793-a2e8-7b8845f631be-attachment.attach"}], "parameters": [{"name": "data", "value": "1"}], "start": 1575025966207, "stop": 1575025966208, "uuid": "d2acb93e-6529-4fd7-97d2-01f7bf9cb11c", "historyId": "71b61181cb38681bfc85e48c867026dd", "testCaseId": "133a8e3ccd283ba22e290157fe855949", "fullName": "scripts.test_fixture.TestLogin#test_login_3", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_fixture"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47A72RD"}, {"name": "thread", "value": "6108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_fixture"}]}