{"name": "test_login_3[2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_fixture.TestLogin object at 0x000002C7D28B9F98>, data = 2\n\n    def test_login_3(self, data):\n        \"\"\"记住密码登录\"\"\"\n        allure.attach(\"输入用户名\", \"输入用户名username_3\")\n        print(\"输入用户名\")\n        allure.attach(\"输入密码\", \"输入用户名password_3\")\n        print(\"输入密码\")\n        allure.attach(\"点击登录\", \"登录成功\")\n        print(\"点击登录\")\n        print(data)\n>       assert False\nE       assert False\n\nscripts\\test_fixture.py:40: AssertionError"}, "description": "记住密码登录", "attachments": [{"name": "输入用户名username_3", "source": "d9266ae0-3398-47ff-87e7-7eb440e91a8a-attachment.attach"}, {"name": "输入用户名password_3", "source": "e30af92f-a167-4802-85d4-e62bed12981a-attachment.attach"}, {"name": "登录成功", "source": "bbd881f9-96d6-48cd-b13d-bd8bbf4532e3-attachment.attach"}], "parameters": [{"name": "data", "value": "2"}], "start": 1575025966249, "stop": 1575025966251, "uuid": "a067d96f-6853-4353-a86f-c28b61a82046", "historyId": "3fa21cf732c1a3ca798649c5798ea1f0", "testCaseId": "133a8e3ccd283ba22e290157fe855949", "fullName": "scripts.test_fixture.TestLogin#test_login_3", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_fixture"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47A72RD"}, {"name": "thread", "value": "6108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_fixture"}]}